import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { BookOpen, ClipboardCheck, LogOut, Plus, Users } from 'lucide-react'
import './App.css'

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:3333/api'
type Turma = { id: number; nome: string; periodo: string; professor: string }
type Aluno = { id: number; nome: string; matricula: string; email: string | null }
type Usuario = { id: number; nome: string; email: string }

async function request(path: string, options?: RequestInit) { const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data }

function App() {
  const [usuario, setUsuario] = useState<Usuario | null>(() => JSON.parse(localStorage.getItem('usuario') ?? 'null'))
  const [cadastro, setCadastro] = useState(false); const [erro, setErro] = useState('')
  const [turmas, setTurmas] = useState<Turma[]>([]); const [alunos, setAlunos] = useState<Aluno[]>([]); const [aba, setAba] = useState<'gestao' | 'chamada'>('gestao'); const [turmaId, setTurmaId] = useState<number | null>(null); const [alunosTurma, setAlunosTurma] = useState<Aluno[]>([]); const [status, setStatus] = useState<Record<number, string>>({})
  const carregar = async () => { try { const [t, a] = await Promise.all([request('/turmas'), request('/alunos')]); setTurmas(t); setAlunos(a); setTurmaId((old) => old ?? t[0]?.id ?? null) } catch (e) { setErro(e instanceof Error ? e.message : 'Erro ao carregar dados.') } }
  useEffect(() => { if (usuario) carregar() }, [usuario])
  useEffect(() => { if (turmaId) request(`/turmas/${turmaId}/alunos`).then((dados: Aluno[]) => { setAlunosTurma(dados); setStatus(Object.fromEntries(dados.map((a) => [a.id, 'PRESENTE']))) }).catch(() => undefined); else setAlunosTurma([]) }, [turmaId])
  async function autenticar(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setErro(''); try { const data = await request(cadastro ? '/auth/cadastro' : '/auth/login', { method: 'POST', body: JSON.stringify({ nome: form.get('nome'), email: form.get('email'), senha: form.get('senha') }) }); localStorage.setItem('usuario', JSON.stringify(data)); setUsuario(data) } catch (e) { setErro(e instanceof Error ? e.message : 'Nao foi possivel continuar.') } }
  async function cadastrar(event: FormEvent<HTMLFormElement>, rota: string) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request(rota, { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); event.currentTarget.reset(); await carregar() } catch (e) { setErro(e instanceof Error ? e.message : 'Erro ao salvar.') } }
  async function vincular(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!turmaId) return; const id = new FormData(event.currentTarget).get('alunoId'); await request(`/turmas/${turmaId}/alunos`, { method: 'POST', body: JSON.stringify({ alunoId: Number(id) }) }); setTurmaId(null); setTimeout(() => setTurmaId(turmaId), 0) }
  async function salvarChamada() { if (!turmaId || !alunosTurma.length) return; try { await request('/chamadas', { method: 'POST', body: JSON.stringify({ turmaId, dataAula: new Date().toISOString().slice(0, 10), registros: alunosTurma.map((a) => ({ alunoId: a.id, status: status[a.id] })) }) }); setErro('Chamada salva com sucesso.') } catch (e) { setErro(e instanceof Error ? e.message : 'Erro ao salvar.') } }
  if (!usuario) return <main className="auth"><section className="auth-card"><div className="auth-brand"><ClipboardCheck /> Chamada<span>+</span></div><h1>{cadastro ? 'Crie sua conta' : 'Bem-vindo de volta'}</h1><p>{cadastro ? 'Cadastre-se para organizar suas materias e alunos.' : 'Entre para acessar suas chamadas.'}</p><form onSubmit={autenticar}>{cadastro && <input name="nome" placeholder="Seu nome" required />}<input name="email" type="email" placeholder="Email" required /><input name="senha" type="password" minLength={6} placeholder="Senha" required /><button>{cadastro ? 'Criar conta' : 'Entrar'}</button></form>{erro && <small className="error">{erro}</small>}<button className="link" onClick={() => { setCadastro(!cadastro); setErro('') }}>{cadastro ? 'Ja tenho uma conta' : 'Ainda nao tenho conta'}</button></section></main>
  return <main className="app"><header><div className="brand"><ClipboardCheck size={20} /> Chamada<span>+</span></div><nav><button className={aba === 'gestao' ? 'active' : ''} onClick={() => setAba('gestao')}><BookOpen size={16} />Gestao</button><button className={aba === 'chamada' ? 'active' : ''} onClick={() => setAba('chamada')}><Users size={16} />Chamada</button></nav><button className="logout" title="Sair" onClick={() => { localStorage.removeItem('usuario'); setUsuario(null) }}><LogOut size={18} /></button></header><div className="page"><div className="title"><p>OLA, {usuario.nome.toUpperCase()}</p><h1>{aba === 'gestao' ? 'Organize sua turma' : 'Registrar chamada'}</h1></div>{erro && <div className="notice">{erro}</div>}{aba === 'gestao' ? <section className="manage"><form className="card" onSubmit={(e) => cadastrar(e, '/turmas')}><BookOpen /><h2>Adicionar materia</h2><input name="nome" placeholder="Nome da materia" required /><input name="periodo" placeholder="Periodo (ex.: 2026.2)" required /><input name="professor" defaultValue={usuario.nome} placeholder="Professor responsavel" required /><button><Plus size={17} />Cadastrar materia</button></form><form className="card" onSubmit={(e) => cadastrar(e, '/alunos')}><Users /><h2>Adicionar aluno</h2><input name="nome" placeholder="Nome completo" required /><input name="matricula" placeholder="Matricula" required /><input name="email" type="email" placeholder="Email (opcional)" /><button><Plus size={17} />Cadastrar aluno</button></form><form className="card" onSubmit={vincular}><ClipboardCheck /><h2>Vincular aluno</h2><select value={turmaId ?? ''} onChange={(e) => setTurmaId(Number(e.target.value))} required><option value="">Escolha a materia</option>{turmas.map((t) => <option key={t.id} value={t.id}>{t.nome}</option>)}</select><select name="alunoId" required><option value="">Escolha o aluno</option>{alunos.map((a) => <option key={a.id} value={a.id}>{a.nome}</option>)}</select><button>Vincular aluno</button></form></section> : <section className="call card"><select value={turmaId ?? ''} onChange={(e) => setTurmaId(Number(e.target.value))}><option value="">Escolha a materia</option>{turmas.map((t) => <option key={t.id} value={t.id}>{t.nome}</option>)}</select>{alunosTurma.length ? alunosTurma.map((a) => <div className="student" key={a.id}><span><b>{a.nome}</b><small>{a.matricula}</small></span><select value={status[a.id] ?? 'PRESENTE'} onChange={(e) => setStatus({ ...status, [a.id]: e.target.value })}><option value="PRESENTE">Presente</option><option value="FALTA">Falta</option><option value="JUSTIFICADO">Justificado</option></select></div>) : <p className="empty">Cadastre uma materia, alunos e vincule-os para iniciar.</p>}<button onClick={salvarChamada} disabled={!alunosTurma.length}>Salvar chamada</button></section>}</div></main>
}
export default App
